name: CI
on:
  push:
    branches:
      - master
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Generate layout.json
        run: |
          cd ./B300
          python build.py
      - name: Commit changes
        run: |
          git add ./B300/layout.json
          git add ./B300/manifest.json
          git commit -m "[CI] Build Task"
          git push